### PR TITLE
Fix lost millisecond precision

### PR DESCRIPTION
**Pull request by juise**
Before:
2020-04-13T10:34:22.000766Z r01.aaa.ru WARNING aaa[4685]
2020-04-13T10:34:22.000984Z r01.aaa.ru WARNING aaa[4685]
2020-04-13T10:34:23.000220Z r01.aaa.ru WARNING aaa[4685]
2020-04-13T10:34:23.000430Z r01.aaa.ru WARNING aaa[4685]
2020-04-13T10:34:23.000774Z r01.aaa.ru WARNING aaa[4685]
2020-04-13T10:34:23.000852Z r01.aaa.ru WARNING aaa[4685]

After:
2020-04-13T12:46:28.504894Z r01.aaa.ru NOTICE hbr[28998]
2020-04-13T12:46:28.506583Z r01.aaa.ru NOTICE hbr[28998]
2020-04-13T12:46:28.506583Z r01.aaa.ru NOTICE hbr[28998]
2020-04-13T12:46:28.506583Z r01.aaa.ru NOTICE hbr[28998]

### CODE REVIEW

**Comment by schlagert** [comment]
Hi and thanks for the Fix. I will look into it tomorrow.

**Comment by schlagert** [comment]
I'm sorry, but I don't really see the problem you try to point out in the description.

If I run the the following snippet
```erlang
lists:foreach(
  fun(_) ->
          T = os:timestamp(),
          Utc = syslog_lib:get_utc_datetime(T),
          io:format("~s~n", [syslog_lib:format_rfc5424_date(Utc)]),
          timer:sleep(100)
  end, lists:seq(1, 10)).
```
with the current HEAD, I get the following output
```
2020-04-15T15:12:10.683370+02:00
2020-04-15T15:12:10.784738+02:00
2020-04-15T15:12:10.885736+02:00
2020-04-15T15:12:10.986766+02:00
2020-04-15T15:12:11.087672+02:00
2020-04-15T15:12:11.188696+02:00
2020-04-15T15:12:11.289679+02:00
2020-04-15T15:12:11.390681+02:00
2020-04-15T15:12:11.492674+02:00
2020-04-15T15:12:11.593668+02:00
```
which seems to be fine.

Looking at the patch I see that there's a correction of the microsecond remainder to `1000000`. However, I think the remainder of `1000` is correct. If I recall correctly, the unit passed to the function is microsecond and the function will separate the value into two components: a millisecond-resolution `datetime` object and the remaining number of microseconds. That means, in the second-based representation `0.XXXYYY`s, the microsecond portion should only include the `Y`s  because the `X`s are already part of the `datetime` object.

Please correct me if I'm wrong.

**Comment by juise** [comment]
Hello!

Your code snippet is absolutely correct, and the result is correct too. In your example, you pass the result of
`T = os:timestamp()`
to
`syslog_lib:get_utc_datetime(T)`
where
`T = {MegaSecs = 1587, Secs = 20338, MicroSecs = 81942}`.

Pay attention, here, the **MicroSecs is 10^6**, i.e. it's a `milliseconds *  1000 + microseconds` - 81 millisecond and 942 microseconds.

The function `get_utc_datetime` (as you know :) ) has two function clauses:
```
get_utc_datetime(SystemTime) when is_integer(SystemTime), SystemTime > 0 ->
  ...
 MicroSecs = SystemTime rem 1000,
  ...
  {Datetime, MicroSecs};
get_utc_datetime({MegaSecs, Secs, MicroSecs}) ->
  ...
  {Datetime, MicroSecs}.
```
The code from your snippet is matched to the second clause, result -`MicroSecs` as-is in 10^6 precision. But in my case, the `Systemtime` it's an integer (the result of `erlang:system_time(millisecond)`) instead of a tuple (the result of `os:timestamp()`). So it's matched to the first clause, result - `MicroSecs` in 10^3 precision.

The code:
```
lists:foreach(
  fun(_) ->
          T = erlang:system_time(millisecond),
          Utc = syslog_lib:get_utc_datetime(T),
          io:format("~s~n", [syslog_lib:format_rfc5424_date(Utc)]),
          timer:sleep(100)
  end, lists:seq(1, 10)).
```
gives:
```
1970-01-19T11:50:19.000734+03:00
1970-01-19T11:50:19.000835+03:00
1970-01-19T11:50:19.000936+03:00
1970-01-19T11:50:19.000037+03:00
1970-01-19T11:50:19.000138+03:00
1970-01-19T11:50:19.000239+03:00
1970-01-19T11:50:19.000340+03:00
1970-01-19T11:50:19.000441+03:00
1970-01-19T11:50:19.000542+03:00
1970-01-19T11:50:19.000643+03:00
```

sorry for TLDR; ))

**Comment by schlagert** [comment]
OMG, how could I __not__ see this... *facepalm*

Thank you so much for the clarification and of course the patch!

**Pull request merged**
