### PR TITLE
More configurable message header contents (and test fixes)

### PR DESCRIPTION
**Pull request by GlenWalker**
* Support use of application metadata value from lager message for appname
* Allow value of hostname field of messages to be partially configured
* Determine hostname field for message when a logger is created instead of
  recalculating it as each message is logged (RFC 3164)
* Ensure tests will pass when run in other timezones
* Don't assume 127.0.0.1 resolves to "localhost" in tests, currently it
  resolves to ip6-localhost and ip6-loopback
  (see also https://github.com/travis-ci/travis-ci/issues/8780)
* Fix IP address regex (matched dynamic hostnames generated by Travis-CI such
  as travis-job-glenwalker-syslog-141260066)

### CODE REVIEW

**Comment by schlagert** [comment]
Hi and thanks for your contribution! I'm just back from vacation and still trying to catch up what's happened at work. I'll review your changes as soon as possible.

**Comment by GlenWalker** [comment]
That's excellent news.

The story behind both main updates - using the lager application metadata, and supporting the short hostname - is that we are trying to keep our logging consistent as we make a few changes.

One change we are making is a switch from using -sname to using -name, in order to allow hostname validation for distributed Erlang using SSL to work. This change means the value of node() changes, which had a few flow on effects, including to logging via syslog.

The other change was to switch from lager_syslog to syslog_lager_backend to get RFC 5424 support, where we wanted to keep the application field of log messages the same as they were so records that end up in logstash are consistent over time.

> Do you really need the hostname_transform configuration option?
We're wanting to keep the short hostname in our syslog records for consistency with historical logs, and with log records that come from Python and also use the short name, and I couldn't think of a cleaner way to make it happen than providing a config option.

> I know that a bare hostname is allowed by RFC 5424 but there's a clear preference that should be respected. ... However, the default value should then be long, do you agree?
If this project was completely new I would absolutely go for the fully qualified hostname as default for RFC 5424, as it is more compliant. I set the default to none so behaviour wouldn't change between versions, to avoid surprises for anyone already using this project. If you're happy to change the default to long I would support that, as I prefer RFC comliance :)

**Comment by schlagert** [comment]
Ok, that makes totally sense for me.

Regarding the default value, you're totally right, backwards compatibility is more important to me. Changing the default value is something, I'll schedule for the 4.0.0 release. I'm currently planing proper `logger` support (OTP 21), this will make some changes in the configuration necessary.

I'll merge this PR and fix some formatting in a separate commit.

**Comment by GlenWalker** [comment]
Awesome, thanks! Looking forward to logger support, we have a few dependencies needing updates for OTP 21, as well as our own code.

**Comment by schlagert** [comment]
Version `3.4.4` has just been deployed to [hex.pm](https://hex.pm/packages/syslog_app/3.4.4).

**Pull request merged**
